"""add source_id column to alerts

Revision ID: aa16dc79e71a
Revises: 
Create Date: 2025-11-05 21:44:34.813093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa16dc79e71a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('source_id', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('received_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('raw_payload', sa.JSON(), nullable=True))
    op.drop_column('alerts', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('alerts', 'raw_payload')
    op.drop_column('alerts', 'received_at')
    op.drop_column('alerts', 'source_id')
    # ### end Alembic commands ###
