"""updated schema

Revision ID: c7d9895fca67
Revises: 84ed0a6c193c
Create Date: 2025-11-06 23:33:56.557364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d9895fca67'
down_revision: Union[str, Sequence[str], None] = '84ed0a6c193c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alerts', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_alerts_source'), table_name='alerts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alerts_source'), 'alerts', ['source'], unique=False)
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alerts', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alerts', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
